### ISSUE TITLE
Issue a new release ?

### ISSUE THREAD

**Issue by kiorky** [subchen/frep#11]
as #10 is merged, would you mind publishing another release to have shiny portable linux binaries ? :smile:

**Comment by subchen** [comment]
Yes, will release it later with rpm & deb package.

**Comment by kiorky** [comment]
Fantastic :).
For the impatients, and lazy: https://github.com/corpusops/frep/releases/tag/1.3.4-alpineworking

**Comment by subchen** [comment]
`1.3.5` released

**Comment by kiorky** [comment]
:+1:
