### ISSUE TITLE
How to access environment inside the range?

### ISSUE THREAD

**Issue by markmadlangbayan** [subchen/frep#12]
Hi there,

I want to access `.ENV.Secret` inside the range.  How do I do that?

```
{{- range (splitList "," .Env.XMPP_JVBS) }}
Component "{{.}}"
    component_secret "{{.ENV.Secret}}"
{{- end }}
```

Thanks!

**Comment by subchen** [comment]
You can use `$.Env.Secret` inside the range. The `$` is a root context.

**Comment by markmadlangbayan** [comment]
Perfect it worked, thank you for the quick reply!
