### ISSUE TITLE
Is it a bug or what ?

### ISSUE THREAD

**Issue by yingzhuo** [subchen/frep#17]
Hi,

I am using a template as below:
```
作者:
    姓名: {{ .author.name }}
    邮件: {{ .author.email }}
```

```bash
frep /path/to/template -e "author.name=应卓" -e "author.email=yingzhor@gmail.com" --dryrun
```

output:

```txt
作者:
    姓名: <no value>
    邮件: <no value>
```

I was wondering maybe if the key contains `.` will cause golang's template rendering bug.

frep version: 

```
Name:       frep
Version:    1.3.7
Patches:    68
Git branch: tags/v1.3.7
Git commit: 9eca7e8f14390b28f08255bb34d987dffd3f9b10
Built:      Tue, 19 Mar 2019 07:11:21 +0000
Go version: go1.11
OS/Arch:    darwin/amd64
```

**Comment by subchen** [comment]
Yes, the `-e` flag only support simple key-value pair, the nested object does not support.

You can try following solutions:
1. Please convert key from `author.name` to `author_name`.
2. Use `{{ index . "author.name" }}` to get value from `author.name`.

**Comment by yingzhuo** [comment]
Thank you.
