### ISSUE TITLE
Can you publish a docker image?

### ISSUE THREAD

**Issue by tonglil** [subchen/frep#3]
Hi, I would like to use this in a CI environment. Can you publish a docker image to docker hub when you create releases please?

Let me know if you would like any help.

If you have issues with using Travis to automate this, check out http://beta.drone.io/ (it has flexible config) (example CI config: https://github.com/drone-plugins/drone-docker/blob/master/.drone.yml).

**Comment by subchen** [comment]
publish docker images: 
- `subchen/frep:1.3.1`
- `subchen/frep:latest`
