### ISSUE TITLE
Unable to install on macOS : Invalid formula

### ISSUE THREAD

**Issue by olgaakrekhovetska** [subchen/frep#40]
Error on installing frep using homebrew.

System setup: macOS Monterey Version 12.4 

% brew install subchen/tap/frep
==> Tapping subchen/tap
Cloning into '/usr/local/Homebrew/Library/Taps/subchen/homebrew-tap'...
remote: Enumerating objects: 180, done.
remote: Counting objects: 100% (32/32), done.
remote: Compressing objects: 100% (25/25), done.
remote: Total 180 (delta 14), reused 19 (delta 7), pack-reused 148
Receiving objects: 100% (180/180), 32.90 KiB | 1.37 MiB/s, done.
Resolving deltas: 100% (65/65), done.
**Error: Invalid formula: /usr/local/Homebrew/Library/Taps/subchen/homebrew-tap/Formula/gometalinter.rb
gometalinter: wrong number of arguments (given 1, expected 0)
Error: Cannot tap subchen/tap: invalid syntax in tap!**

**Comment by subchen** [comment]
Fixed, please check

**Comment by olgaakrekhovetska** [comment]
Thanks @subchen, it works now:)
