### ISSUE TITLE
Please preserve file permissions

### ISSUE THREAD

**Issue by jaisingh** [subchen/frep#5]
File perms (specifically +x ) are lost when a template file is run though frep. Please preserve originating file permissions when writing out the rendered template.

**Comment by subchen** [comment]
Yes, you are right. I'll fix it.

**Comment by subchen** [comment]
@jaisingh Sorry for later response, I cannot reproduce this issue.

```bash
$ ll examples/nginx.conf
-rwxrwxrwx 1 ubuntu ubuntu 235 Nov 27 01:54 examples/nginx.conf*

$ frep-1.3.3-linux-amd64 --overwrite examples/nginx.conf.in

$ ll examples/nginx.conf
-rwxrwxrwx 1 ubuntu ubuntu 235 Nov 27 01:56 examples/nginx.conf*
```

Could you provide your details？

**Comment by n-arakawa** [comment]
`frep-1.3.10-linux-amd64` seems do not preserve file permissions.


On the other hand, I  do
`chmod --reference "from_file" "to_file" ; chmod a-w "to_file"`

Dropping write permission prevents editing generated file carelessly.

**Comment by subchen** [comment]
`frep` don't update the output file permission when file exists.
