### ISSUE TITLE
配置文件中的数组类型怎么判断最后一个元素呢

### ISSUE THREAD

**Issue by holy-root** [subchen/frep#8]
比如
环境变量：
{
    host_ip": {
        "127.0.0.1:8081",
        "127.0.0.1:8082"
    }
}
配置文件中的配置项：
host={{range .host_ip}}{{.}},{{end}}

用frep替换之后的结果是：
host=127.0.0.1:8081,127.0.0.1:8082,

怎么去掉最后8082后面的,呢

**Comment by subchen** [comment]
你可以用 `host={{range $index, $elem := .host_ip}}{{if gt $index 0}},{{end}}{{$elem}}{{end}}`

或者 `host={{.host_ip | join ","}}`
